### ISSUE TITLE
only for Jscholarship, whose ids are resolvable url, the same value used to assign to RepoCopy.externalIds field should also be assigned to the RepoCopy.accessURL

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/nihms-submission#115]
@Trumbore please let me know if you need me to clarify this ticket.

**Comment by emetsger** [comment]
I think this issue will end up being subsumed by the work I'm doing now on handling `Deposit`s in `SUBMITTED` state, so assigning this ticket to myself!

**Comment by emetsger** [comment]
Fixed in #124.
